// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC84p8H3Y87xOAgkf2x2PosiJ7CNfTO8Mo',
    appId: '1:744850158885:web:121a0206a084ce9c23d6cc',
    messagingSenderId: '744850158885',
    projectId: 'times-87de9',
    authDomain: 'times-87de9.firebaseapp.com',
    storageBucket: 'times-87de9.appspot.com',
    measurementId: 'G-7VG5VXZH5T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqwGEguiaUzvPx0VteY_UfsP1TMLvAH8o',
    appId: '1:744850158885:android:cd2252207ba5a7ea23d6cc',
    messagingSenderId: '744850158885',
    projectId: 'times-87de9',
    storageBucket: 'times-87de9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjc8nAOM_z5CmpK_P_KFq-XcG8knvMrYY',
    appId: '1:744850158885:ios:c882c30a5ad8192923d6cc',
    messagingSenderId: '744850158885',
    projectId: 'times-87de9',
    storageBucket: 'times-87de9.appspot.com',
    iosBundleId: 'com.example.time',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjc8nAOM_z5CmpK_P_KFq-XcG8knvMrYY',
    appId: '1:744850158885:ios:c882c30a5ad8192923d6cc',
    messagingSenderId: '744850158885',
    projectId: 'times-87de9',
    storageBucket: 'times-87de9.appspot.com',
    iosBundleId: 'com.example.time',
  );
}
